config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get     'esci'  => 'sessions#esci', as: 'esci'
  post    'cercaservizi' =>'ricerches#servizivicini'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'servizis/:id/Aggpref'  => 'favorites#create', as: 'aggiungi'
  get    '/preferiti'          => 'users#listapreferiti', as: 'preferiti'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :servizis,          only: [:create, :destroy, :show]
  resources :recensionis,       only: [:create, :destroy]
  resources :domandes,          only: [:create, :destroy, :edit, :update]
  resources :ricerches,          only: [:create, :destroy]
  resource :session, only: [:create]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/servizi.rb
class Servizi < ApplicationRecord
  geocoded_by :indirizzo
  belongs_to :user
  after_validation :geocode, if: :indirizzo_changed?
  before_save :creacoordinate
  has_many :favorites, dependent: :destroy
  has_many :recensionis, dependent: :destroy
  has_many :domandes, dependent: :destroy
  default_scope -> { order(created_at: :desc)
  }
  mount_uploader :immagini, ImmaginiUploader
  validates :user_id, presence: true
  validates :descrizione, length: { maximum: 300 }
  validate  :limite_immagine
  def creacoordinate
    lat=Geocoder.coordinates(self.indirizzo.split(',').first).first
    lon=Geocoder.coordinates(self.indirizzo.split(',').first).second
    self.latitude=lat
    self.longitude=lon
  end
  private
  def limite_immagine
    if immagini.size > 5.megabytes
       errors.add(:immagini, "Immagine troppo grande")
    end

  end
end

app/controllers/servizis_controller.rb
class ServizisController < ApplicationController
    before_action :logged_in_users, only: [:create, :destroy]
    before_action :userservizio, only: :destroy
  def create
    @servizio = currentuser.servizis.build(servizi_params)
    if @servizio.save
      flash[:success] = "Servizio aggiunto"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end
  def destroy
    Servizi.find(params[:id]).destroy
    flash[:success] = "Cancellazione avvenuta con successo"
    render 'show'
  end
  def show
      @servizi=Servizi.find(params[:id])
      @recensioni=Recensioni.new
      @recensionis=@servizi.recensionis.paginate(page: params[:page])
      @domande=Domande.new
      @domandes=@servizi.domandes.paginate(page: params[:page])
  end
  private
    #Strong parameters (Parametri forti), nel controller possibile soltanto accedere alle chiavi whitelistate descrizione, tipo, indirizzo e nome
    def servizi_params
      params.require(:servizi).permit(:descrizione, :tipo, :indirizzo, :nome, :immagini)
    end
    def userservizio
      @servizio = currentuser.servizis.find_by(id: params[:id])
      redirect_to root_url if @servizio.nil?
    end
end

app/helpers/servizis_helper.rb
module ServizisHelper
end

app/views/servizis/_servizi.html.erb
<li id="Servizi-<%= servizi.id %>">
  <span class="nome"><%= link_to servizi.nome, servizi_path(servizi.id)%></span>
  <span class="indirizzo"><%= servizi.indirizzo %>
  <span class="tipo"><%= servizi.tipo %></span>
  <span class="content"><%= servizi.descrizione %>

  </span>
  <span class="timestamp">
    Creato: <%= time_ago_in_words(servizi.created_at) %> ago.
    <% if currentuser==servizi.user %>
      <%= link_to "Cancella", servizi, :method => :delete,
                                       data: { confirm: "Sicuro?" } %>
    <% end %>
  </span>
</li>

app/views/servizis/show.html.erb
<li id="Servizi-<%= @servizi.id %>">
  <span class="nome"><%= @servizi.nome %></span>
  <span class="tipo"><%= @servizi.tipo %></span>
  <span class="content"><%= @servizi.descrizione %>
  <span class="image"> <%= image_tag @servizi.immagini.url if @servizi.immagini? %> </span>
  <span class="preferiti"> <%= link_to "Aggiungi ai preferiti", aggiungi_path(@servizi.id) %> </span>

  </span>
  <span class="timestamp">
    Creato: <%= time_ago_in_words(@servizi.created_at) %> ago.
    <% if currentuser==@servizi.user %>
      <%= link_to "Cancella", @servizi, :method => :delete,
                                       data: { confirm: "Sicuro?" } %>
    <% end %>
  </span>
  <span class="aggiungi">
  <%= link_to "Aggiungi preferiti", aggiungi_path(@servizi.id) %>
  </span>
  <div class="row-md-8" align="left">
    <% if @servizi.recensionis.any? %>
      <h3>Numero Recensioni: (<%= @servizi.recensionis.count %>)</h3>
      <ol class="recensioni">
         <%= render @servizi.recensionis %>
      </ol>
      <%= will_paginate @recensionis %>
    <% end %>
  </div>
  <section class="recensioni_form">
  <%= form_for(@recensioni) do |f| %>
  <%= f.label :titolo %>
  <%= f.text_field :titolo, class: 'form-control' %>
  <br>
  <br>
  <%= f.label :Voto %>
  <%= f.text_field :votoservizio, class: 'form-control' %>
  <br>
  <br>
  <%=f.hidden_field 'servizi_id', :value => @servizi.id %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Scrivi recensione" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <% end %>

      </section>
  <div class="row-md-8" align="right">
    <% if @servizi.domandes.any? %>
      <h3>Numero Domande: (<%= @servizi.domandes.count %>)</h3>
      <ol class="domande">
         <%= render @servizi.domandes %>
      </ol>
      <%= will_paginate @domandes %>
    <% end %>
  </div>
  <section class="domande_form">
  <%= form_for(@domande) do |f| %>
  <%=f.hidden_field 'servizio_id', :value => @servizi.id %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Scrivi domanda" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <% end %>
  </section>
</li>